version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.5.3
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    expose:
        - 9300
  kibana:
    image: kibana:6.5.3
    ports:
        - 5601:5601
  redis:
    image: redis:5.0.3-alpine3.8
    ports:
        - 6379:6379
  ts-example-api:
    build: .
    ports:
      - 3000:3000
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - elasticsearch
      - kibana
      - redis
volumes:
    elasticsearch-data:
        driver: local